- name: Coping mongodb repo file 
  ansible.builtin.copy:
    src: mongod.repo 
    dest: /etc/yum.repos.d/mongodb.repo  

- name: Installing MongoDb
  ansible.builtin.yum:
    name: mongodb-org 
    state: present 

- name: Updating MongoDB Config
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Starting MongoDB Service 
  ansible.builtin.service:
    name: mongod  
    state: started
    enabled: yes

- name: Downloading and extracting mongodb schema  
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/mongodb/archive/main.zip
    dest: /tmp 
    remote_src: yes

- name: Loading Catalogue Schema 
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{item}}.js"
    idempotent: yes 
  loop: 
      

# - name: Loading Catalogue Schema 
#   community.mongodb.mongodb_shell:
#     file: "/tmp/mongodb-main/catalogue.js"
#     idempotent: yes

# - name: Loading Users Schema 
#   community.mongodb.mongodb_shell:
#     file: "/tmp/mongodb-main/users.js"
#     idempotent: yes

# curl -s -L -o /tmp/mongodb.zip "https://github.com/stans-robot-project/mongodb/archive/main.zip"

# cd /tmp
# unzip mongodb.zip
# cd mongodb-main
# mongo < catalogue.js
# mongo < users.js