- name: Coping mongodb repo file 
  ansible.builtin.copy:
    src: mongod.repo 
    dest: /etc/yum.repod.d/mongodb.repo  

- name: Installing MongoDb
  ansible.builtin.yum:
    name: mongodb-org 
    state: present 

- name: Updating MongoDB Config
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Starting MongoDB Service 
  ansible.builtin.service:
    name: mongod  
    state: started
    enabled: yes