- name: Creating application user
  ansible.builtin.user:
    name: "{{APPUSER}}" 
    comment: Roboshop Application User
  register: APPUSER_REGISTER

# - name: test 
#   debug:
#    msg: "{{APPUSER_REGISTER}}"